# Generated by Django 5.2 on 2025-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0003_athleteinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleteinfo",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
