# Generated by Django 5.2 on 2025-07-25 15:48

import app_run.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0005_challenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Широта: от -90.0000 до 90.0000",
                        max_digits=6,
                        validators=[app_run.validators.validate_coordinate],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Долгота: от -90.0000 до 90.0000",
                        max_digits=6,
                        validators=[app_run.validators.validate_coordinate],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_run.run"
                    ),
                ),
            ],
        ),
    ]
